# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  imageName: 'jump-the-queue-angular'

stages:
- stage: Build
displayName: Build
jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '6.x'
      checkLatest: true
    displayName: 'Install Node.js'

  - script: |
      cd '$(System.DefaultWorkingDirectory)/angular'
      npm install
      npm run build
    displayName: 'npm Install and Build'

- stage: Docker
displayName: Docker
jobs:
  - job: Docker
    displayName: Docker
    pool:
      vmImage_ ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        repository: $(imageName)
        command: 'build'
        Dockerfile: 'angular/Dockerfile'
      displayName: 'Build the image'
      
    - task: Docker@2
      inputs:
        command: 'login'