version: '3'

services:
    jenkins:
        user: root
        image: jenkins/jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        container_name: 'jenkins'
        networks:
            - cicd
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    sonarqube:
        image: sonarqube:latest
        container_name: 'sonarqube'
        depends_on:
            - db
        ports:
            - '9000:9000'
        networks:
            - cicd
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
            - SONAR_JDBC_USERNAME=sonar
            - SONAR_JDBC_PASSWORD=sonar

    db:
        image: postgres
        container_name: 'db'
        networks:
            - cicd
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar

    nexus:
        image: sonatype/nexus3
        container_name: 'nexus'
        ports:
            - '8085:8081'
            - '8090:8082'
        networks:
            - cicd
        volumes:
            - /nexus-data:/nexus-data

networks:
    cicd:
        driver: bridge
        