apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: jump-the-queue-angular
spec:
  selector:
    matchLabels:
      app: jump-the-queue-angular
  template:
    metadata:
      labels:
        app: jump-the-queue-angular
    spec:
      containers:
      - name: jump-the-queue-angular
        image: localhost:8090/angular
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
