version: '3'

services:
    jenkins:
        user: root
        image: jenkins/jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        container_name: 'jenkins'
        networks:
            - jenkins

    sonarqube:
        image: sonarqube:latest
        container_name: 'sonarqube'
        ports:
            - '9000:9000'
        networks:
            - jenkins
        environment:
            - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar

    db:
        image: postgres
        container_name: 'db'
        networks:
            - jenkins
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar

networks:
    jenkins:
        driver: bridge


        