apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reverse-proxy
  labels:
      name: reverse-proxy
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: angular-svc
            port: 
              number: 80
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: java-svc
            port:
              number: 8081
